name: systeminfo
version: 0.8
summary: Simple program showing system information in C++
description: |
  A program that displays basic information about the system and resources
parts:
  hello:
    plugin: cmake
    source: src

apps:
  systeminfo:
    command: hello