name: systeminfoi
version: '4.2'
summary: Simple program showing system information
description: |
  A program that displays basic information about the system and resources
grade: stable
base: core18
license: GPL-2.0

apps:
  systeminfoi:
    command: systeminfoi
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - personal-files

parts:
  systeminfoi:
    plugin: cmake
    source: .
    build-packages:
      - cmake
      - make
